---

computername: Gibran
hostname: gibran

finder_proxy_icon_hover_delay: 0

safari_show_full_url_in_address_bar: true
safari_open_safe_files_automatically: true
safari_show_status_bar: true
safari_show_developer_menu: true

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - jeromegamez/formulae
  - github/gh
  - aws/tap

homebrew_apps:
  - 1password
  - alfred
  - asdf
  - bartender
  - brave-browser
  - cleanmymac
  - discord
  - docker
  - firefox
  - font-fira-code
  - iterm2
  - multimc
  - paw
  - slack
  - telegram
  - transmit
  - twitch
  - visual-studio-code
  - whatsapp

homebrew_packages:
  - aws-shell
  - awscli
  - aws-sam-cli
  - bash
  - chag
  - composer
  - curl
  - fasd
  - gh
  - git
  - httpie
  - imagemagick
  - jq
  - make
  - node
  - openssh
  - php
  - pkg-config
  - python
  - tree
  - vim
  - wget
  - yadm
  - watch
  - zlib
  - zsh

mas_apps:
  - { name: 1Blocker, id: 1107421413 }
  - { name: CloudMounter, id: 1130254674 }
  - { name: Endel, id: 1484348796 }
  - { name: Evernote, id: 406056744 }
  - { name: HazeOver, id: 430798174 }
  - { name: LastPass, id: 926036361 }
  - { name: Magnet, id: 441258766 }
  - { name: Pages, id: 409201541 }
  - { name: Patterns, id: 429449079 }
  - { name: Scansnap, id: 1211119808 }
  - { name: Soulver, id: 1508732804 }
  - { name: Tweetbot, id: 1384080005 }
  - { name: Unclutter, id: 577085396 }
  - { name: XCode, id: 497799835 }

vscode_extensions:
  - BriteSnow.vscode-toggle-quotes
  - CraigMaslowski.erb
  - Tyriar.sort-lines
  - akamud.vscode-theme-onedark
  - aki77.rails-db-schema
  - aliariff.vscode-erb-beautify
  - bibhasdn.unique-lines
  - bradlc.vscode-tailwindcss
  - castwide.solargraph
  - hjleochen.rails-nav
  - kaiwood.endwise
  - misogi.ruby-rubocop
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vsliveshare.vsliveshare
  - rayhanw.erb-helpers
  - rebornix.ruby
  - ruiquelhas.vscode-lowercase
  - shaharkazaz.git-merger
  - sianglim.slim
  - vincaslt.highlight-matching-tag
  - vortizhe.simple-ruby-erb
  - vscode-icons-team.vscode-icons